### ISSUE TITLE
Request for a meeting on Storage Access API

### ISSUE THREAD

**Issue by johannhof** [privacycg/meetings#11]
Hello, at Mozilla we're interested in moving the [Storage Access API](https://github.com/privacycg/storage-access) forward in the standardization process and resolving the existing [interop issues](https://github.com/privacycg/storage-access/labels/interop) to that effect specifically. We would also like to discuss the current state of developer experience and potential ways to improve documentation/examples for using the Storage Access API.

So we'd like to call for an ad-hoc meeting on Storage Access API. I can compile the agenda in advance based on the above topics and any other things people might want to discuss (happy to take suggestions).

cc @englehardt, @annevk, @johnwilander, @erik-anderson, @Brandr0id 

I don't expect to be able to hold this meeting in 2020 still, so maybe some time in January?

**Comment by TanviHacks** [comment]
Would Thursday January 21st at 10am PST work? @johannhof @Brandr0id @johnwilander @jkarlin @jeremyroman @englehardt.

**Comment by johannhof** [comment]
@TanviHacks That would work for me, thank you.

**Comment by johnwilander** [comment]
I have a conflict 10:30-11:00 that I might be able to move.

**Comment by TanviHacks** [comment]
@johnwilander Let us know if you can move your 10:30.  If so, we can confirm the time.  Thank you!

**Comment by johnwilander** [comment]
Confirmed that my conflicting meeting will be moved.

**Comment by TanviHacks** [comment]
Okay then we are set for January 21st 10am PST.  Using our regular call in details: https://github.com/privacycg/meetings/tree/master/2021/telcons.  Please all mark your calendars.

**Comment by johannhof** [comment]
Preliminary agenda from me, if you have time please take a look and feel free to suggest edits/additions:

**(1) [40 mins] Work through [interop Issues](https://github.com/privacycg/storage-access/labels/interop).**

  * [https://github.com/privacycg/storage-access/issues/25](https://github.com/privacycg/storage-access/issues/25)

    * Firefox is planning to align with Safari behavior, any concerns from Edge?

  * [https://github.com/privacycg/storage-access/issues/36](https://github.com/privacycg/storage-access/issues/36)

    * Browsers seem to align on always rejecting without user gesture in cross-origin iframes, but differ in top-level context behavior (Safari resolves, Edge rejects).

  * [https://github.com/privacycg/storage-access/issues/36](https://github.com/privacycg/storage-access/issues/36)

    * There's a new suggestion for a resolution from Firefox folks, would be great to get feedback on this.

  * [https://github.com/privacycg/storage-access/issues/4](https://github.com/privacycg/storage-access/issues/4)

    * This probably needs a few words in the spec but might otherwise be punted to storage-partitioning.

  * [https://github.com/privacycg/storage-access/issues/2](https://github.com/privacycg/storage-access/issues/2)

    * Firefox and Edge align on this as well as Safari Technology Preview, can we resolve this issue?

**(2) [20 mins] Standardization.**
* Are the spec editors (John and Tess) available to start resolving (inline) spec issues? What do they need help with?
* Can we identify issues that are blockers for standardization and assign someone to move them forward? Potential blockers:

   * inline spec issues

   * [https://github.com/privacycg/storage-access/issues/40](https://github.com/privacycg/storage-access/issues/40)

   * [https://github.com/privacycg/storage-access/issues/50](https://github.com/privacycg/storage-access/issues/50)

   * [https://github.com/privacycg/storage-access/issues/31](https://github.com/privacycg/storage-access/issues/31)

   * [https://github.com/privacycg/storage-access/issues/12](https://github.com/privacycg/storage-access/issues/12) and [https://github.com/privacycg/storage-access/issues/10](https://github.com/privacycg/storage-access/issues/10) (from Edge folks)   

   * [https://github.com/privacycg/storage-access/issues/37](https://github.com/privacycg/storage-access/issues/37)

* Where do we want to move the spec as it matures?
