### ISSUE TITLE
Request for meeting on First-Party Sets acceptance process

### ISSUE THREAD

**Issue by krgovind** [privacycg/meetings#14]
Hi, I'd like to request a meeting focused on discussion about what a standard, cross-browser First-Party Sets acceptance process and policy might look like. We have an [initial proposal](https://github.com/krgovind/first-party-sets#acceptance-process) that I'd like to use as a starting point. 

If possible, I'd like to suggest scheduling the discussion for the hour after the CG telcon on August 12, 2021 (10am-11am~ET~PT). I can share materials and agenda a week in advance if this time is confirmed.

**Comment by TanviHacks** [comment]
Thanks for submitting the issue!  That time should work for the chairs and one of us will help with coordination (assuming you meant PT, right after the regular call).

To give us an idea of how many people will attend, can folks that are interested add a thumbs up here?  Also, to those interested, please comment if you would really like to attend but have a big scheduling conflict with the proposed time - August 12, 2021 (10am-11am PT).

We can finalize the time before our next teleconference and make a verbal announcement during the call.  Thanks!

**Comment by krgovind** [comment]
Sorry, I did indeed mean 10am-11am PT. Corrected the original post.

**Comment by martinthomson** [comment]
I would like to attend, but I have a hard conflict with sleep.  I realize that finding times that work for people in multiple time zones is challenging, but 10am PT is quite challenging for those in Australia.

**Comment by TanviHacks** [comment]
How about 2pm PT on Thursday, August 12th.  That will be 5pm ET, 10 pm in the UK, 11 pm in Germany/France, and Friday  7am in Sydney.

Please thumbs up if that works for you.  Thanks!

**Comment by TanviHacks** [comment]
Okay - lets go with that:

First Party Sets Ad Hoc Meeting
Thursday, August 12th
2pm PT, 5pm ET
Same zoom details and meeting notes as our regular teleconferences

We will also announce at this Thursday's call.  Thanks!

**Comment by krgovind** [comment]
We just published this [UA Policy Proposal document](https://github.com/privacycg/first-party-sets/blob/main/ua_policy_proposal.md) in the explainer repo for discussion during this call.

Proposed agenda:
[10min] Refresher/introduction of use-cases and motivation for FPS
[25min] [FPS Policy Proposal](https://github.com/privacycg/first-party-sets/blob/main/ua_policy_proposal.md)
[20min] Questions and feedback

**Comment by TanviHacks** [comment]
Thanks to Kaustubha and Jeff for presenting, and thanks to the folks who participated!  Notes are up here - https://github.com/privacycg/meetings/blob/main/2021/telcons/08-12-21-FPS-adhoc-minutes.md.
