### ISSUE TITLE
Cross-site cookies standardization

### ISSUE THREAD

**Issue by annevk** [privacycg/meetings#16]
As discussed in the last call it would be good to sort out our collective story around cookies. Tentative agenda for a dedicated meeting:

1. Are the usual cross-site cookies "blocked" or "partitioned"?
2. Do we need opt-in partitioned cookies? And if so, through CHIPS or `requestStorageAccess()`, or something else?
3. How do we organize standardization?
4. Interaction of cross-site cookies and `SameSite=None`.
5. Ephemeral partitioned third-party storage (including cookies) by Brave: https://github.com/privacycg/proposals/issues/18.

**Comment by krgovind** [comment]
Speaking on behalf of Chrome, we'd be interested in this discussion.

**Comment by hober** [comment]
How about the 5th Thursday of March (March 31st), in our usual telcon time slot? @annevk

**Comment by annevk** [comment]
Works for me!

**Comment by bc-pi** [comment]
Will March 31st be put on the calendar? https://www.w3.org/groups/cg/privacycg/calendar

**Comment by annevk** [comment]
@krgovind sounds good, added that to OP.

**Comment by TanviHacks** [comment]
Due to some unforeseen schedule conflicts, we need to postpone this.  We are planning to use our regular Thursday, April 14th teleconference for this ad hoc.  Sorry about the last minute change!

**Comment by samuelweiler** [comment]
This has been rescheduled for 14 April 2022.

**Comment by erik-anderson** [comment]
This has again been rescheduled. We'll now discuss this during our April 28th call.

**Comment by annevk** [comment]
The minutes are now live at https://github.com/privacycg/meetings/blob/main/2022/telcons/04-28-minutes.md thanks to @hober. A follow-up meeting has been proposed in #19. With that I'm closing this issue.

Thanks everyone for participating and also to the chairs for taking care of most things, including rescheduling this more than once!
