### ISSUE TITLE
Request for meeting for JS Membranes proposal

### ISSUE THREAD

**Issue by pes10k** [privacycg/meetings#2]
As per the most recent call, i would like to organize a meeting regarding the https://github.com/privacycg/js-membranes proposal.  Thanks!

**Comment by TanviHacks** [comment]
Hey @pes10k!  Thanks for submitting this.  Can you write down a few bullet points on what you would like to discuss.  Also, would you like to propose some times that work for you?  Or if you are pretty flexible, the chairs can propose a few times.  Then we can see what works best for the folks that are interested in discussing this with you.

Note this is the first time we are doing this, so may take time to fine tune a process.

**Comment by pes10k** [comment]
Thanks @TanviHacks !

The main things I'd like to discuss more on are:

1) Are there other vendors in PrivacyCG who are interested in prototyping / implementing, possibly before Brave is able to?  We are unlikely to start a possible implementation until summer, but if others are interested, I or others at Brave would be very interested in working on a joint / common implementation in any runtime.
2) More broadly, would be very interested to get a sense of which bucket other folks fall in: (i) interested in seeing what happens if others plan to implement, (ii) planning on implementing, (iii) no interest, (iv) other.
3) What do others think about the possible overhead of the approach?
4) The spec doesn't require any tainting or similar; if a script is fetched and executed from example.org, and that script injects another script from other.org, this proposal doesn't provide anyway for tying the behavior of the other.org script to example.org.  Is this a problem?  My sense is that tracking script providence would make this functionality even more useful, but that the approach is sufficiently useful itself that it makes sense to be its own proposal.  Would be very interested in others thoughts
5) Are others pursing / planning different approaches to the same problem?

I am very flexible on timing and location :)

**Comment by TanviHacks** [comment]
Hi @pes10k!  Would Thursday, March 19th at 10:00 am PST (right after the PING call) or Monday, March 23rd at 1:00 pm PST work?

Please also invite people who you think would be interested in attending.

**Comment by pes10k** [comment]
Thanks @TanviHacks !

I think this would mostly hinge on whether other vendors were interested.  Would any number of @kdzwinel @johnwilander @englehardt @ehsan @erik-anderson @TanviHacks be interested in the call?  If so, either time works for me (and likely other Brave-side folks)

**Comment by deian** [comment]
Following up on https://github.com/privacycg/js-membranes/issues/1#issuecomment-601465467 happy to hop on call if it would be useful; if its 1PM monday, I can wiggle things around and try to  make that time slot

**Comment by TanviHacks** [comment]
We are a little late for Monday, so how about Thursday March 26th at 10am PST (right after our regular Privacy CG teleconference).  Would that work?

**Comment by pes10k** [comment]
that would work just fine with me

**Comment by deian** [comment]
works for me

**Comment by TanviHacks** [comment]
Okay sounds great!  I'll send an email to the group.

**Comment by pes10k** [comment]
@TanviHacks could you share connection details for the call?  Zoom link etc?  Or if its the same as the PrivacyCG call, i can re-post here too

**Comment by TanviHacks** [comment]
We will be using the same details as the teleconference, which is right before this meeting - https://mozilla.zoom.us/j/769153986.  We can also continue in the same cryptad - https://cryptpad.w3ctag.org/code/#/2/code/edit/ZrkcuhmVbx1OGyWlTX5L0j8T/.  If that call ends early, we may start early if we have everyone we expect.

See https://github.com/privacycg/meetings/blob/master/2020/telcons/README.md for more dial in details.

Thanks!

**Comment by TanviHacks** [comment]
Thanks for the lively discussion!  Meeting notes are here - https://github.com/privacycg/meetings/blob/master/2020/telcons/03-26-membranes-minutes.md.  Closing out this meeting request.
