### ISSUE TITLE
Spring 2020 Virtual F2F

### ISSUE THREAD

**Issue by hober** [privacycg/meetings#3]
We'll be having our first F2F in May of this year!

We had hoped to have an in-person meeting, but current global situation and in light of [W3C guidance](https://w3c.github.io/Guide/meetings/continuity.html), we will have a virtual meeting instead.

## Logistics

* When: 13–14 May, 15:00–19:00 UTC

| Start  | End | Location |
| ------ | --- | -------- |
| 00:00 (Midnight next day) | 04:00 | Tokyo |
| 01:00 (next day) | 05:00 | Sydney |
| 08:00 | 11:00 | San Francisco |
| 11:00 | 15:00 (3 PM) | Boston |
| 16:00 (4 PM) | 20:00 (8 PM) | London |
| 17:00 (5 PM) | 21:00 (9 PM) | Brussels |

## Agenda

Anyone can request that specific issues or PRs be added to the F2F agenda by adding the `agenda+F2F` label to the issue or PR. Here's a list of [every issue and PR that currently has this label](https://github.com/search?q=org%3Aprivacycg+label%3Aagenda%2BF2F).

**Comment by hober** [comment]
I'm in PDT (UTC-7).

**Comment by pes10k** [comment]
I'm also in PDT

**Comment by chrisn** [comment]
I'm in UTC+1

**Comment by fastest963** [comment]
I'm in EDT (UTC-4)

**Comment by npdoty** [comment]
I'm also in Eastern Daylight Time (UTC-4)

**Comment by erik-anderson** [comment]
I'm in PDT.

**Comment by melanierichards** [comment]
+1 for PDT

**Comment by dsenecal04** [comment]
PDT for me too

**Comment by sammacbeth** [comment]
I'm in CET (UTC+1)

**Comment by danielcompton** [comment]
I live in New Zealand but work on PDT (Sun - Thu)

**Comment by benjaminsavage** [comment]
I'm in London

**Comment by scottlow** [comment]
+1 for PDT

**Comment by hober** [comment]
As we've settled on dates and times and we've [published the details](https://github.com/privacycg/meetings/tree/master/2020/05-virtual), I'm closing this issue.
