### ISSUE TITLE
TPAC: Storage Access API Future

### ISSUE THREAD

**Issue by johannhof** [privacycg/meetings#33]
I'd like to discuss the state and outlook of some of the various improvements and additions to the Storage Access API (after graduation), such as:

- [DOM Storage support](https://github.com/privacycg/storage-access/issues/102)
- Top-level Storage Access as proposed by [Chrome](https://github.com/privacycg/requestStorageAccessFor) and [Firefox](https://github.com/bvandersloot-mozilla/top-level-storage-access) and how to converge these
- [Forward-Declared SAA](https://github.com/privacycg/storage-access/issues/83)
- [Login Status integration](https://github.com/samuelgoto/login-status-api#storage-access-api)
- [Request Header integrations](https://github.com/privacycg/storage-access/issues/130) for SAA

We'll probably not get to all of those, would be good to know if folks are interested in covering anything in particular.

cc @bvandersloot-mozilla @helenyc @cfredric @annevk

**Comment by johannhof** [comment]
@privacycg/chairs sorry for the late addition to the schedule, if this isn't a good use of our time I can take it to breakouts instead :)

**Comment by arichiv** [comment]
Slides: https://docs.google.com/presentation/d/1SOCYJvUzjJHsVLlzqlYVKtU7yg-RWhGJWW4Om6dCinE/edit#slide=id.g243c8331bfd_0_0
