### ISSUE TITLE
TPAC: Pop-up Partitioning / Isolation

### ISSUE THREAD

**Issue by johannhof** [privacycg/meetings#34]
@privacycg/chairs sorry for the last minute request, @arichiv and I were wondering if we could spend just a few minutes at TPAC discussing the problems and potential solutions for https://github.com/privacycg/proposals/issues/7, as Ari recently published a [new proposal](https://arichiv.github.io/opener-storage-partitioning/) on Chromium side.

**Comment by hober** [comment]
We'll try to fit it in!

**Comment by johannhof** [comment]
Slides are here: https://docs.google.com/presentation/d/1INuMF3t6Px3OF2aezbACAFtYnfnBI26hjyJrYM5yi6I/edit#slide=id.g27d95086681_0_0
