### ISSUE TITLE
TPAC 2024

### ISSUE THREAD

**Issue by johannhof** [privacycg/meetings#38]
@privacycg/chairs Did we request time on this year's TPAC schedule? It's likely we'll have topics to discuss. We should also do a call for topics with the group.

**Comment by erik-anderson** [comment]
We put in a request for time. Keeping this issue active to cover setting an agenda.

**Comment by arichiv** [comment]
https://github.com/explainers-by-googlers/partitioned-popins

**Comment by cfredric** [comment]
I'd like to discuss [Storage Access Headers](https://github.com/cfredric/storage-access-headers) and give a demo in Chrome.

**Comment by martinthomson** [comment]
Draft Agenda, as posted to the list:

* Intro (10 min)
* Status updates from open work items (20 min) All of the Editors
* Non-Cookie Storage: https://github.com/privacycg/saa-non-cookie-storage (15 min) Ari
* Consent Management: https://github.com/privacycg/proposals/issues/48 (15 min)
* Google’s cookie plans and implications for our work (15 min)
* AOB (balance)

**Comment by AramZS** [comment]
We will be able to do a status update for the work on GPC.
