### ISSUE TITLE
Request for meeting on Bounce Tracking Proposal

### ISSUE THREAD

**Issue by TanviHacks** [privacycg/meetings#5]
As discussed [here](https://github.com/privacycg/proposals/issues/6#issuecomment-606875511), a few folks are interested in an ad-hoc meeting dedicated to Bounce Tracking.

**Comment by TanviHacks** [comment]
How is Thursday, April 23rd at 10 am PDT, right after the regular teleconference?

cc @johnwilander @pes10k

**Comment by pes10k** [comment]
sure, that works for me, thanks!

**Comment by johnwilander** [comment]
Works for me too.

**Comment by johannhof** [comment]
I'd like to join that discussion :)

**Comment by englehardt** [comment]
That works for me as well! I'm looking forward to the discussion.

**Comment by TanviHacks** [comment]
Great!  We are set for Thursday, April 23rd at 10 am PDT to discuss Bounce Tracking.  We'll send out an email announcement next week.

@johnwilander please come prepared with an Agenda.  We can use the same call in details and same cryptpad as we do for our teleconference.  I'll work on getting a volunteer to scribe.  Thanks!

**Comment by hober** [comment]
This happened today. Closing.
