### ISSUE TITLE
September 2020 Virtual F2F

### ISSUE THREAD

**Issue by erik-anderson** [privacycg/meetings#8]
We'll be having our second F2F in September!

Given the ongoing global situation and in light of [W3C guidance](https://w3c.github.io/Guide/meetings/continuity.html), this will be a virtual meeting just like our initial F2F.

## Logistics

* When: September 16-17, 15:00–19:00 UTC

| Start  | End | Location |
| ------ | --- | -------- |
| 00:00 (Midnight next day) | 04:00 | Tokyo |
| 01:00 (next day) | 05:00 | Sydney |
| 08:00 | 12:00 | San Francisco |
| 11:00 | 15:00 (3 PM) | Boston |
| 16:00 (4 PM) | 20:00 (8 PM) | London |
| 17:00 (5 PM) | 21:00 (9 PM) | Brussels |

## Agenda

Anyone can request that specific issues or PRs be added to the F2F agenda by adding the `agenda+F2F` label to the issue or PR. Here's a list of [every issue and PR that currently has this label](https://github.com/search?q=org%3Aprivacycg+label%3Aagenda%2BF2F).

**Comment by samuelweiler** [comment]
Tuesday 15 Sept is the usual WebAppSec meeting, 1800-1900 UTC (the last hour of the planned f2f window).  We should coordinate with WebAppSec in any case, but particularly so if we're scheduling on top of them.

**Comment by erik-anderson** [comment]
We previously announced this on our telecons: we settled on Wednesday and Thursday (the 16th and 17th).

**Comment by TanviHacks** [comment]
We had this virtual face to face last month.  Meeting minutes can be found here https://github.com/privacycg/meetings/tree/master/2020/09-virtual
