### ISSUE TITLE
Request for meeting on Standardizing Do Not Sell (GPC)

### ISSUE THREAD

**Issue by asoltani** [privacycg/meetings#9]
Per previous discussions, I would like to organize a meeting regarding the GPC proposal: https://github.com/privacycg/proposals/issues/10 .  More info here: https://globalprivacycontrol.org/faq .

Perhaps there's time after the next PrivacyCG meeting: Thursday Dec 10 @ 10-11am?

**Comment by erik-anderson** [comment]
PING is not meeting this week, so another option would be this week at 9am-10am PST.

Do you have a preference for this week at 9am vs. next week at 10am?

**Comment by asoltani** [comment]
I think next week is a bit better just to give folks some advance notice.  I'll send a note to the PrivacyCG list as well

**Comment by TanviHacks** [comment]
Okay, sounds good!  So then we are set for Thursday December 10th 10:00 am - 11:00 am PST, right after our regular teleconference.  We will use the same notes doc and same zoom details, so folks can just stay on the line.

If folks can add a thumbs up here to express their interest, it will give us an idea of how many people will attend.

@asoltani please go ahead and send an email to the group, including this issue and letting them know the date/time.  We will also followup and announce it again next week when we send out the teleconference agenda.

Minutes will be here - https://docs.google.com/document/d/1DZEhS1UHJ1PKxt5ZwKmn5LZ4bo10UFyNXeLp2dUuzRM/edit#

Zoom Meeting ID: 769 153 986
    Zoom native client: https://mozilla.zoom.us/j/769153986
    Zoom web client: https://zoom.us/wc/join/769153986?pwd=?

**Comment by michael-oneill** [comment]
+1

**Comment by ebrawer** [comment]
Looking forward to this.

**Comment by asoltani** [comment]
Just an update: we've been added to the end of the PrivacyCG agenda so for folks planning to join the adhoc, we'll likely kickoff before 10am in reality: https://github.com/privacycg/meetings/blob/master/2020/telcons/12-10-agenda.md

**Comment by TanviHacks** [comment]
Looks like we never closed this one out so doing that now.  The minutes from the meeting are here - https://github.com/privacycg/meetings/blob/main/2020/telcons/12-10-minutes.md.  Thank you!
